
spring:
  application:
    name: backend_capstone_project

  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    # uri: mongodb://mongo:27017/capstone_db
    uri: mongodb://localhost:27017/capstone_db

server:
  address: 0.0.0.0
  port: 8080